package refresh

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/bakw00ds/yakos/internal/hooks/registry"
)

// ---- helpers ----------------------------------------------------------------

const testBin = "/opt/yakos/bin/yakos"

func hooksImplRepoRoot(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs(filepath.Join("..", "..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	return root
}

var hooksImplFixtures = []string{
	"proj-in-sync", "proj-local-hook", "proj-missing-settings",
	"proj-stale-hook", "proj-superseded-matcher",
}

func copyTree(t *testing.T, src, dst string) {
	t.Helper()
	err := filepath.Walk(src, func(p string, fi os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(src, p)
		target := filepath.Join(dst, rel)
		if fi.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		data, err := os.ReadFile(p) //nolint:gosec
		if err != nil {
			return err
		}
		return os.WriteFile(target, data, 0o644) //nolint:gosec
	})
	if err != nil {
		t.Fatalf("copyTree: %v", err)
	}
}

// fixtureProject copies a stock refresh fixture into a temp project.
func fixtureProject(t *testing.T, name string) (proj, home string) {
	t.Helper()
	tmp := t.TempDir()
	proj = filepath.Join(tmp, "project")
	home = filepath.Join(tmp, "home")
	for _, d := range []string{proj, filepath.Join(home, ".claude", "agents")} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			t.Fatal(err)
		}
	}
	copyTree(t, filepath.Join("..", "..", "cmd", "yakos", "testdata", "fixtures", "refresh", name), proj)
	return proj, home
}

func runImpl(t *testing.T, proj, home string, impl HooksImpl) (string, error) {
	t.Helper()
	var buf bytes.Buffer
	_, err := Run(Config{
		YakosRoot:    hooksImplRepoRoot(t),
		ProjectPaths: []string{proj},
		HooksImpl:    impl,
		YakosBinary:  testBin,
		Writer:       &buf,
		ErrWriter:    &buf,
		HomeDir:      home,
	})
	return buf.String(), err
}

func readSettings(t *testing.T, proj string) []byte {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(proj, ".claude", "settings.json")) //nolint:gosec
	if err != nil {
		t.Fatal(err)
	}
	return b
}

// commands returns every hook command in settings, in document order per
// event (events sorted), as "event|command".
func commands(t *testing.T, data []byte) []string {
	t.Helper()
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		t.Fatal(err)
	}
	var out []string
	hm := hooksMap(m)
	events := make([]string, 0, len(hm))
	for e := range hm {
		events = append(events, e)
	}
	sortStrings(events)
	for _, e := range events {
		for _, en := range asList(hm[e]) {
			for _, h := range asList(hooksList(toMap(en))) {
				out = append(out, e+"|"+commandOf(toMap(h)))
			}
		}
	}
	return out
}

func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j] < s[j-1]; j-- {
			s[j], s[j-1] = s[j-1], s[j]
		}
	}
}

func isAllowlisted(name string) bool {
	for _, n := range GoReadyAllowlist() {
		if n == name {
			return true
		}
	}
	return false
}

// ---- tests ------------------------------------------------------------------

// Default (no flag, nothing persisted) must be byte-identical to the
// pre-A-3 output. The golden files were generated by a binary built at
// 1837bee (main before this change).
func TestHooksImpl_DefaultMatchesGoldenAt1837bee(t *testing.T) {
	for _, name := range hooksImplFixtures {
		t.Run(name, func(t *testing.T) {
			golden, err := os.ReadFile(filepath.Join("testdata", "golden-bash", name+".settings.json")) //nolint:gosec
			if err != nil {
				t.Fatal(err)
			}
			for _, impl := range []HooksImpl{"", HooksImplBash} {
				proj, home := fixtureProject(t, name)
				if _, err := runImpl(t, proj, home, impl); err != nil {
					t.Fatal(err)
				}
				if got := readSettings(t, proj); !bytes.Equal(got, golden) {
					t.Fatalf("impl=%q settings.json differs from 1837bee golden:\n%s", impl, byteDiff(golden, got))
				}
			}
		})
	}
}

// Default run must not create .yakos.yml (no persistence side effect).
func TestHooksImpl_DefaultDoesNotWriteYakosYml(t *testing.T) {
	proj, home := fixtureProject(t, "proj-missing-settings")
	if _, err := runImpl(t, proj, home, ""); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(proj, ".yakos.yml")); err == nil {
		t.Fatal(".yakos.yml created by a default refresh")
	}
}

func TestHooksImpl_GoRewritesEveryHookCommand(t *testing.T) {
	proj, home := fixtureProject(t, "proj-missing-settings")
	if _, err := runImpl(t, proj, home, HooksImplGo); err != nil {
		t.Fatal(err)
	}
	cmds := commands(t, readSettings(t, proj))
	if len(cmds) == 0 {
		t.Fatal("no commands")
	}
	for _, c := range cmds {
		cmd := c[strings.Index(c, "|")+1:]
		if !isGoCommand(cmd) {
			t.Errorf("go mode left a non-Go command: %s", c)
		}
	}
}

func TestHooksImpl_GoPreservesProjectLocalHook(t *testing.T) {
	proj, home := fixtureProject(t, "proj-local-hook")
	if _, err := runImpl(t, proj, home, HooksImplGo); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(readSettings(t, proj)), "kanban-stop.sh") {
		t.Fatal("project-local hook dropped by go mode")
	}
}

func TestHooksImpl_HybridRewritesOnlyAllowlist(t *testing.T) {
	proj, home := fixtureProject(t, "proj-missing-settings")
	if _, err := runImpl(t, proj, home, HooksImplHybrid); err != nil {
		t.Fatal(err)
	}
	goSeen := map[string]bool{}
	for _, c := range commands(t, readSettings(t, proj)) {
		cmd := c[strings.Index(c, "|")+1:]
		if name, ok := goHookName(cmd); ok {
			if !isAllowlisted(name) {
				t.Errorf("hybrid rewrote non-allowlisted hook %s", name)
			}
			goSeen[name] = true
			continue
		}
		if n := hookNameFromTemplateCommand(cmd); isAllowlisted(n) {
			t.Errorf("hybrid left allowlisted hook %s as bash", n)
		}
	}
	for _, n := range GoReadyAllowlist() {
		if !goSeen[n] {
			t.Errorf("allowlisted hook %s not registered as Go", n)
		}
	}
}

func TestHooksImpl_PersistedValueHonoredThenFlagOverrides(t *testing.T) {
	proj, home := fixtureProject(t, "proj-missing-settings")
	if _, err := runImpl(t, proj, home, HooksImplHybrid); err != nil {
		t.Fatal(err)
	}
	if v, ok, err := ReadPersistedHooksImpl(proj); err != nil || !ok || v != HooksImplHybrid {
		t.Fatalf("persisted = %q,%v,%v; want hybrid", v, ok, err)
	}
	hybrid := readSettings(t, proj)

	// No flag: persisted hybrid is kept.
	out, err := runImpl(t, proj, home, "")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "hooks-impl: hybrid (persisted)") {
		t.Fatalf("output does not report persisted hybrid:\n%s", out)
	}
	if !bytes.Equal(hybrid, readSettings(t, proj)) {
		t.Fatal("no-flag run changed a hybrid settings.json")
	}

	// Flag overrides and re-persists.
	if _, err := runImpl(t, proj, home, HooksImplGo); err != nil {
		t.Fatal(err)
	}
	if v, _, _ := ReadPersistedHooksImpl(proj); v != HooksImplGo {
		t.Fatalf("persisted after override = %q, want go", v)
	}
	if _, err := runImpl(t, proj, home, ""); err != nil {
		t.Fatal(err)
	}
	for _, c := range commands(t, readSettings(t, proj)) {
		if !strings.Contains(c, testBin+" hook run ") {
			t.Fatalf("persisted go not honored: %s", c)
		}
	}
}

// bash -> go -> bash must land back on the golden bytes, and switching must
// replace in place (never leave both forms registered).
func TestHooksImpl_SwitchRoundTripNoDuplicates(t *testing.T) {
	proj, home := fixtureProject(t, "proj-missing-settings")
	golden, _ := os.ReadFile(filepath.Join("testdata", "golden-bash", "proj-missing-settings.settings.json")) //nolint:gosec
	bashCmds := commands(t, golden)
	for _, impl := range []HooksImpl{HooksImplBash, HooksImplHybrid, HooksImplGo, HooksImplHybrid, HooksImplBash} {
		if _, err := runImpl(t, proj, home, impl); err != nil {
			t.Fatal(err)
		}
		if n := len(commands(t, readSettings(t, proj))); n != len(bashCmds) {
			t.Fatalf("after %s: %d commands, want %d (duplicates?)", impl, n, len(bashCmds))
		}
	}
	if !bytes.Equal(readSettings(t, proj), golden) {
		t.Fatal("bash->hybrid->go->hybrid->bash did not return to golden bytes (hook order or content drifted)")
	}
}

// Hook order inside each event must be identical across impls.
func TestHooksImpl_HookOrderUnchanged(t *testing.T) {
	names := func(cmds []string) []string {
		var out []string
		for _, c := range cmds {
			ev := c[:strings.Index(c, "|")]
			cmd := c[strings.Index(c, "|")+1:]
			n := hookNameFromTemplateCommand(cmd)
			if g, ok := goHookName(cmd); ok {
				n = g
			}
			out = append(out, ev+"|"+n)
		}
		return out
	}
	base, home := fixtureProject(t, "proj-missing-settings")
	if _, err := runImpl(t, base, home, HooksImplBash); err != nil {
		t.Fatal(err)
	}
	want := names(commands(t, readSettings(t, base)))
	for _, impl := range []HooksImpl{HooksImplHybrid, HooksImplGo} {
		if _, err := runImpl(t, base, home, impl); err != nil {
			t.Fatal(err)
		}
		got := names(commands(t, readSettings(t, base)))
		if strings.Join(got, ",") != strings.Join(want, ",") {
			t.Fatalf("%s reordered hooks:\n got %v\nwant %v", impl, got, want)
		}
	}
}

func TestHooksImpl_TwoConsecutiveRunsByteIdentical(t *testing.T) {
	for _, impl := range []HooksImpl{HooksImplBash, HooksImplGo, HooksImplHybrid} {
		t.Run(string(impl), func(t *testing.T) {
			p1, h1 := fixtureProject(t, "proj-missing-settings")
			p2, h2 := fixtureProject(t, "proj-missing-settings")
			if _, err := runImpl(t, p1, h1, impl); err != nil {
				t.Fatal(err)
			}
			if _, err := runImpl(t, p2, h2, impl); err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(readSettings(t, p1), readSettings(t, p2)) {
				t.Fatal("two fresh runs differ")
			}
			first := readSettings(t, p1)
			if _, err := runImpl(t, p1, h1, ""); err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(first, readSettings(t, p1)) {
				t.Fatal("second run on same project changed bytes")
			}
		})
	}
}

// Fail closed: an unregistered hook under go/hybrid is an error, the run
// aborts non-zero, and neither settings.json nor .yakos.yml is touched.
func TestHooksImpl_UnregisteredHookFailsClosed(t *testing.T) {
	for _, tc := range []struct {
		impl    HooksImpl
		missing string
	}{
		{HooksImplGo, "path-log"},
		{HooksImplHybrid, "cycle-counter"},
	} {
		t.Run(string(tc.impl), func(t *testing.T) {
			orig := registeredHooks
			t.Cleanup(func() { registeredHooks = orig })
			registeredHooks = func() []string {
				var out []string
				for _, n := range registry.Names() {
					if n != tc.missing {
						out = append(out, n)
					}
				}
				return out
			}
			proj, home := fixtureProject(t, "proj-missing-settings")
			before := readSettings(t, proj)
			hooksBefore, _ := os.ReadDir(filepath.Join(proj, "scripts"))
			_, err := runImpl(t, proj, home, tc.impl)
			if err == nil {
				t.Fatal("want error for unregistered hook, got nil")
			}
			if !strings.Contains(err.Error(), tc.missing) || !strings.Contains(err.Error(), "no Go implementation registered") {
				t.Fatalf("error does not name the hook: %v", err)
			}
			if !bytes.Equal(before, readSettings(t, proj)) {
				t.Fatal("settings.json modified despite refusal")
			}
			if _, err := os.Stat(filepath.Join(proj, ".yakos.yml")); err == nil {
				t.Fatal(".yakos.yml persisted despite refusal")
			}
			if hooksAfter, _ := os.ReadDir(filepath.Join(proj, "scripts")); len(hooksAfter) != len(hooksBefore) {
				t.Fatal("hook scripts synced despite refusal")
			}
		})
	}
}

func TestHooksImpl_InvalidValueRejected(t *testing.T) {
	proj, home := fixtureProject(t, "proj-missing-settings")
	if _, err := runImpl(t, proj, home, "rust"); err == nil {
		t.Fatal("want error for --hooks-impl rust")
	}
	if err := os.WriteFile(filepath.Join(proj, ".yakos.yml"), []byte("hooks_impl: nope\n"), 0o644); err != nil { //nolint:gosec
		t.Fatal(err)
	}
	if _, err := runImpl(t, proj, home, ""); err == nil {
		t.Fatal("want error for corrupt persisted hooks_impl")
	}
}

func TestPersistHooksImpl_PreservesExistingContent(t *testing.T) {
	dir := t.TempDir()
	orig := "# project config\nname: demo\nsupervisor:\n  enabled: true\n"
	if err := os.WriteFile(filepath.Join(dir, ".yakos.yml"), []byte(orig), 0o644); err != nil { //nolint:gosec
		t.Fatal(err)
	}
	if err := PersistHooksImpl(dir, HooksImplGo); err != nil {
		t.Fatal(err)
	}
	got, _ := os.ReadFile(filepath.Join(dir, ".yakos.yml")) //nolint:gosec
	if string(got) != orig+"hooks_impl: go\n" {
		t.Fatalf("append: %q", got)
	}
	if err := PersistHooksImpl(dir, HooksImplHybrid); err != nil {
		t.Fatal(err)
	}
	got, _ = os.ReadFile(filepath.Join(dir, ".yakos.yml")) //nolint:gosec
	if string(got) != orig+"hooks_impl: hybrid\n" {
		t.Fatalf("replace: %q", got)
	}
}

// Consistency with the real registry: the hybrid allowlist is sorted, every
// entry is registered and marked GoReady there, and go mode covers every
// hook in the shipped template.
func TestHooksImpl_AllowlistAndTemplateAgreeWithRegistry(t *testing.T) {
	reg := map[string]registry.Entry{}
	for _, e := range registry.All() {
		reg[e.Name] = e
	}
	var want []string
	for _, e := range registry.All() {
		if e.GoReady {
			want = append(want, e.Name)
		}
	}
	got := GoReadyAllowlist()
	if strings.Join(got, ",") != strings.Join(want, ",") {
		t.Errorf("hybrid list %v != registry GoReady set %v", got, want)
	}
	if !isAllowlisted("path-log") {
		t.Error("path-log (GoReady since A-1) missing from the hybrid list")
	}
	for i, n := range got {
		if i > 0 && got[i-1] >= n {
			t.Errorf("hybrid list not sorted at %q", n)
		}
		if _, ok := reg[n]; !ok {
			t.Errorf("%q not registered", n)
		}
	}
	data, err := os.ReadFile(filepath.Join(hooksImplRepoRoot(t), "lib", "settings", "settings.template.json")) //nolint:gosec
	if err != nil {
		t.Fatal(err)
	}
	var tmpl map[string]any
	if err := json.Unmarshal(data, &tmpl); err != nil {
		t.Fatal(err)
	}
	if err := ValidateHooksImpl(HooksImplGo, tmpl); err != nil {
		t.Fatalf("shipped template has hooks with no Go implementation: %v", err)
	}
}

func TestGoHookNameAndCanonical(t *testing.T) {
	for cmd, want := range map[string]string{
		"yakos hook run cycle-counter":                         "cycle-counter.sh",
		"/usr/local/bin/yakos hook run path-log":               "path-log.sh",
		"${CLAUDE_PROJECT_DIR}/scripts/hooks/cycle-counter.sh": "cycle-counter.sh",
	} {
		if got := canonicalHookName(cmd); got != want {
			t.Errorf("canonicalHookName(%q) = %q, want %q", cmd, got, want)
		}
	}
	if _, ok := goHookName("yakos hooks install x"); ok {
		t.Error("`yakos hooks ...` must not parse as a Go hook command")
	}
}

func TestHooksImpl_DryRunReportsImplAndWritesNothing(t *testing.T) {
	proj, home := fixtureProject(t, "proj-missing-settings")
	before := readSettings(t, proj)
	var buf bytes.Buffer
	_, err := Run(Config{
		YakosRoot: hooksImplRepoRoot(t), ProjectPaths: []string{proj},
		HooksImpl: HooksImplGo, YakosBinary: testBin, DryRun: true, Writer: &buf, ErrWriter: &buf, HomeDir: home,
	})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(buf.String(), "hooks-impl: go (flag)") {
		t.Fatalf("dry-run does not report the impl:\n%s", buf.String())
	}
	if !bytes.Equal(before, readSettings(t, proj)) {
		t.Fatal("dry-run modified settings.json")
	}
	if _, err := os.Stat(filepath.Join(proj, ".yakos.yml")); err == nil {
		t.Fatal("dry-run persisted .yakos.yml")
	}
}

func TestHooksImpl_CommandsUseAbsoluteBinaryPath(t *testing.T) {
	proj, home := fixtureProject(t, "proj-missing-settings")
	if _, err := runImpl(t, proj, home, HooksImplGo); err != nil {
		t.Fatal(err)
	}
	for _, c := range commands(t, readSettings(t, proj)) {
		cmd := c[strings.Index(c, "|")+1:]
		if !strings.HasPrefix(cmd, testBin+" hook run ") {
			t.Errorf("not an absolute-path Go command: %s", cmd)
		}
	}
}

// Moving the binary rewrites commands in place (order kept, no duplicates).
func TestHooksImpl_BinaryPathChangeReplacesInPlace(t *testing.T) {
	// hybrid, so bash and Go commands share matcher blocks: a remove+append
	// replace would reorder them.
	proj, home := fixtureProject(t, "proj-missing-settings")
	if _, err := runImpl(t, proj, home, HooksImplHybrid); err != nil {
		t.Fatal(err)
	}
	before := commands(t, readSettings(t, proj))
	var buf bytes.Buffer
	if _, err := Run(Config{YakosRoot: hooksImplRepoRoot(t), ProjectPaths: []string{proj}, YakosBinary: "/usr/local/bin/yakos",
		Writer: &buf, ErrWriter: &buf, HomeDir: home}); err != nil {
		t.Fatal(err)
	}
	after := commands(t, readSettings(t, proj))
	if len(after) != len(before) {
		t.Fatalf("count changed %d -> %d", len(before), len(after))
	}
	moved := 0
	for i := range after {
		if strings.Replace(before[i], testBin, "/usr/local/bin/yakos", 1) != after[i] {
			t.Fatalf("entry %d: %q -> %q", i, before[i], after[i])
		}
		if strings.Contains(after[i], "/usr/local/bin/yakos") {
			moved++
		}
	}
	if moved == 0 {
		t.Fatal("no command picked up the new binary path")
	}
}

func TestHooksImpl_PathWithSpaceIsQuotedAndParsed(t *testing.T) {
	c := goCommand("/Users/a b/bin/yakos", "path-log")
	if c != "'/Users/a b/bin/yakos' hook run --impl go path-log" {
		t.Fatalf("quoting: %s", c)
	}
	if n, ok := goHookName(c); !ok || n != "path-log" {
		t.Fatalf("parse: %q %v", n, ok)
	}
	if _, ok := goHookName("/usr/bin/other hook run x"); ok {
		t.Fatal("non-yakos binary parsed as a Go hook command")
	}
}

func TestHooksImpl_GoCommandPinsTierAndParserAcceptsLegacy(t *testing.T) {
	if got := goCommand("/x/yakos", "secret-scan"); got != "/x/yakos hook run --impl go secret-scan" {
		t.Fatalf("goCommand must pin the Go tier explicitly, got %q", got)
	}
	cases := map[string]struct {
		name string
		ok   bool
	}{
		"/x/yakos hook run --impl go secret-scan": {"secret-scan", true},
		"/x/yakos hook run secret-scan":           {"secret-scan", true}, // legacy (A-3)
		"/x/yakos hook run --impl bash x":         {"", false},
		"/x/yakos hook run --impl go":             {"", false},
		"/x/yakos hook run --other go x":          {"", false},
		"/x/yakos hook run --impl go x y":         {"", false},
		"/x/yakos hook run --impl go -x":          {"", false},
	}
	for in, want := range cases {
		n, ok := goHookName(in)
		if ok != want.ok || n != want.name {
			t.Errorf("goHookName(%q) = %q,%v want %q,%v", in, n, ok, want.name, want.ok)
		}
	}
}

func TestHooksImpl_DefaultBinaryResolvesAbsoluteAndWarnsWhenTemporary(t *testing.T) {
	orig := runningBinary
	t.Cleanup(func() { runningBinary = orig })
	runningBinary = func() (string, error) { return filepath.Join(os.TempDir(), "yakos-x", "yakos"), nil }
	proj, home := fixtureProject(t, "proj-missing-settings")
	var buf bytes.Buffer
	if _, err := Run(Config{YakosRoot: hooksImplRepoRoot(t), ProjectPaths: []string{proj}, HooksImpl: HooksImplHybrid,
		Writer: &buf, ErrWriter: &buf, HomeDir: home}); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(buf.String(), "looks temporary") {
		t.Fatalf("no temp-path warning:\n%s", buf.String())
	}
	// Compare decoded commands (JSON-unescaped, shell-quoted as needed) so
	// Windows backslash paths are handled.
	wantCmd := goCommand(filepath.Join(os.TempDir(), "yakos-x", "yakos"), "cycle-counter")
	found := false
	for _, c := range commands(t, readSettings(t, proj)) {
		if strings.HasSuffix(c, "|"+wantCmd) {
			found = true
		}
	}
	if !found {
		t.Fatalf("resolved binary path not embedded; want %q", wantCmd)
	}
	// Installed path: no warning.
	runningBinary = func() (string, error) { return "/opt/yakos/bin/yakos", nil }
	buf.Reset()
	p2, h2 := fixtureProject(t, "proj-missing-settings")
	if _, err := Run(Config{YakosRoot: hooksImplRepoRoot(t), ProjectPaths: []string{p2}, HooksImpl: HooksImplHybrid,
		Writer: &buf, ErrWriter: &buf, HomeDir: h2}); err != nil {
		t.Fatal(err)
	}
	if strings.Contains(buf.String(), "looks temporary") {
		t.Fatal("spurious temp warning for an installed path")
	}
}

func TestHooksImpl_GoWarnsAboutNonGoReadyHooks(t *testing.T) {
	proj, home := fixtureProject(t, "proj-missing-settings")
	out, err := runImpl(t, proj, home, HooksImplGo)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "not yet marked GoReady") || !strings.Contains(out, "secret-scan") {
		t.Fatalf("go mode did not warn naming non-GoReady hooks:\n%s", out)
	}
	if strings.Contains(out, "path-log,") || strings.Contains(out, ": path-log") {
		t.Fatalf("warning lists a GoReady hook:\n%s", out)
	}
	proj2, home2 := fixtureProject(t, "proj-missing-settings")
	out, _ = runImpl(t, proj2, home2, HooksImplHybrid)
	if strings.Contains(out, "not yet marked GoReady") {
		t.Fatal("hybrid must not print the go-mode warning")
	}
}

func TestPersistHooksImpl_KeepsInlineCommentAndCRLF(t *testing.T) {
	dir := t.TempDir()
	write := func(s string) {
		if err := os.WriteFile(filepath.Join(dir, ".yakos.yml"), []byte(s), 0o644); err != nil { //nolint:gosec
			t.Fatal(err)
		}
	}
	read := func() string { b, _ := os.ReadFile(filepath.Join(dir, ".yakos.yml")); return string(b) } //nolint:gosec

	write("name: x\nhooks_impl: go   # keep me\nother: 1\n")
	if err := PersistHooksImpl(dir, HooksImplHybrid); err != nil {
		t.Fatal(err)
	}
	if got := read(); got != "name: x\nhooks_impl: hybrid   # keep me\nother: 1\n" {
		t.Fatalf("inline comment lost: %q", got)
	}
	if v, _, _ := ReadPersistedHooksImpl(dir); v != HooksImplHybrid {
		t.Fatalf("read back %q", v)
	}

	write("name: x\r\nhooks_impl: go\r\nother: 1\r\n")
	if err := PersistHooksImpl(dir, HooksImplBash); err != nil {
		t.Fatal(err)
	}
	if got := read(); got != "name: x\r\nhooks_impl: bash\r\nother: 1\r\n" {
		t.Fatalf("CRLF lost: %q", got)
	}
	if v, ok, err := ReadPersistedHooksImpl(dir); err != nil || !ok || v != HooksImplBash {
		t.Fatalf("CRLF read back %q %v %v", v, ok, err)
	}

	write("name: x\r\nother: 1")
	if err := PersistHooksImpl(dir, HooksImplGo); err != nil {
		t.Fatal(err)
	}
	if got := read(); got != "name: x\r\nother: 1\r\nhooks_impl: go\r\n" {
		t.Fatalf("CRLF append: %q", got)
	}
}

// A binary path with a single quote and a space must round-trip through the
// quoting and the parser: no duplicates, reruns are no-ops, and switching
// back to bash leaves no Go commands behind.
func TestHooksImpl_QuotePathRoundTrip(t *testing.T) {
	const weird = "/we ird/it's dir/yakos"
	if n, ok := goHookName(goCommand(weird, "path-log")); !ok || n != "path-log" {
		t.Fatalf("parse of %q: %q %v", goCommand(weird, "path-log"), n, ok)
	}
	proj, home := fixtureProject(t, "proj-missing-settings")
	golden, _ := os.ReadFile(filepath.Join("testdata", "golden-bash", "proj-missing-settings.settings.json")) //nolint:gosec
	want := len(commands(t, golden))
	run := func(impl HooksImpl) string {
		var buf bytes.Buffer
		if _, err := Run(Config{YakosRoot: hooksImplRepoRoot(t), ProjectPaths: []string{proj}, HooksImpl: impl,
			YakosBinary: weird, Writer: &buf, ErrWriter: &buf, HomeDir: home}); err != nil {
			t.Fatal(err)
		}
		if n := len(commands(t, readSettings(t, proj))); n != want {
			t.Fatalf("after %q: %d commands, want %d", impl, n, want)
		}
		return buf.String()
	}
	run(HooksImplHybrid)
	run(HooksImplGo)
	before := readSettings(t, proj)
	if out := run(""); !strings.Contains(out, "added=0 removed=0") {
		t.Fatalf("rerun not a no-op:\n%s", out)
	}
	if !bytes.Equal(before, readSettings(t, proj)) {
		t.Fatal("rerun changed bytes")
	}
	run(HooksImplBash)
	if !bytes.Equal(readSettings(t, proj), golden) {
		t.Fatal("switch back to bash left leftovers / did not match golden")
	}
}

func TestEphemeralBinary_CoversPrivateTmp(t *testing.T) {
	t.Setenv("TMPDIR", "/elsewhere")
	for _, p := range []string{"/private/tmp/x/yakos", "/tmp/x/yakos", "/Users/a/yakOS-wt-foo/bin/yakos"} {
		if !ephemeralBinary(p) {
			t.Errorf("%s not flagged ephemeral", p)
		}
	}
	if ephemeralBinary("/opt/yakos/bin/yakos") {
		t.Error("installed path flagged")
	}
}

// byteDiff renders a self-explaining difference between want and got: sizes,
// CR counts (CRLF checkout problems), and the first differing lines.
func byteDiff(want, got []byte) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "want %d bytes (%d CR), got %d bytes (%d CR)\n",
		len(want), bytes.Count(want, []byte("\r")), len(got), bytes.Count(got, []byte("\r")))
	wl := strings.Split(string(want), "\n")
	gl := strings.Split(string(got), "\n")
	shown := 0
	for i := 0; i < len(wl) || i < len(gl); i++ {
		var w, g string
		if i < len(wl) {
			w = wl[i]
		}
		if i < len(gl) {
			g = gl[i]
		}
		if w != g {
			fmt.Fprintf(&sb, "line %d:\n- %q\n+ %q\n", i+1, w, g)
			if shown++; shown >= 8 {
				sb.WriteString("... (more differences)\n")
				break
			}
		}
	}
	return sb.String()
}
