package main

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestWantREPL(t *testing.T) {
	cases := []struct {
		name string
		g    replGate
		tty  bool
		want bool
	}{
		{"plain on a terminal", replGate{}, true, true},
		{"plain, stdin piped", replGate{}, false, false},
		{"--runtime codex", replGate{runtime: "codex"}, true, true},
		{"--runtime claude-sdk is a native launch", replGate{runtime: "claude-sdk"}, true, false},
		{"--native keeps the exec path", replGate{native: "claude", runtime: "claude"}, true, false},
		{"--no-repl", replGate{noREPL: true}, true, false},
		{"--dry-run", replGate{dryRun: true}, true, false},
		{"--print-agents", replGate{printAgents: true}, true, false},
		{"--print-env", replGate{printEnv: true}, true, false},
		{"--share-terminal", replGate{shareTerminal: true}, true, false},
		{"--direct", replGate{direct: true}, true, false},
		{"--continue", replGate{cont: true}, true, false},
		{"--resume", replGate{resume: "abc"}, true, false},
		{"--fork-session", replGate{fork: true}, true, false},
		{"--ide", replGate{ide: true}, true, false},
		{"--bare", replGate{bare: true}, true, false},
		{"--strict-mcp", replGate{strictMCP: true}, true, false},
		{"passthrough after --", replGate{passthrough: []string{"-p"}}, true, false},
		{"networked flags", replGate{daemonFlags: true}, true, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := wantREPL(tc.g, tc.tty); got != tc.want {
				t.Errorf("wantREPL = %v, want %v", got, tc.want)
			}
		})
	}
}

// startArgv runs `yakos start <args>` in process with a stub runtime on PATH and
// returns the argv that would be exec'd, with the fixture paths normalised.
func startArgv(t *testing.T, args ...string) string {
	t.Helper()
	if runtime.GOOS == "windows" {
		t.Skip("stub runtimes are shell scripts")
	}
	home, repo := setupStartProject(t, "argvproj")
	bin := t.TempDir()
	for _, rt := range []string{"claude", "codex"} {
		if err := os.WriteFile(filepath.Join(bin, rt), []byte("#!/bin/sh\nexit 0\n"), 0o755); err != nil {
			t.Fatal(err)
		}
	}
	t.Setenv("HOME", home)
	t.Setenv("PATH", bin+string(os.PathListSeparator)+os.Getenv("PATH"))
	t.Setenv("YAKOS_ROOT", "")
	orig := startExecFnOverride
	t.Cleanup(func() { startExecFnOverride = orig })
	var got []string
	startExecFnOverride = func(argv0 string, argv []string, env []string) error {
		got = append([]string{"argv0=" + argv0}, argv...)
		return nil
	}
	runStart(repoRoot(t), append([]string{"argvproj", "--no-agents"}, args...))
	s := strings.Join(got, "\n") + "\n"
	for from, to := range map[string]string{bin: "<bin>", repo: "<repo>", home: "<home>"} {
		s = strings.ReplaceAll(s, from, to)
	}
	// macOS resolves /var to /private/var in some paths.
	for from, to := range map[string]string{"/private<": "<"} {
		s = strings.ReplaceAll(s, from, to)
	}
	return s
}

// TestNativeKeepsTodaysArgv pins the argv `yakos start --native <rt>` execs to
// the one `--runtime <rt>` built before the REPL existed (K-154: the vendor-TUI
// path is unchanged). The goldens were generated by the pre-REPL binary from
// `--runtime <rt>`; --native must reproduce them even on a terminal, where the
// REPL would otherwise win. A piped `--runtime <rt>` must reproduce them too.
func TestNativeKeepsTodaysArgv(t *testing.T) {
	orig := stdinIsTerminal
	t.Cleanup(func() { stdinIsTerminal = orig })
	for _, rt := range []string{"claude", "codex"} {
		want, err := os.ReadFile(filepath.Join("testdata", "start_native_"+rt+".argv.golden"))
		if err != nil {
			t.Fatal(err)
		}
		for _, tc := range []struct {
			name string
			tty  bool
			args []string
		}{
			{"native on a terminal", true, []string{"--native", rt}},
			{"native piped", false, []string{"--native", rt}},
			{"runtime piped", false, []string{"--runtime", rt}},
		} {
			t.Run(rt+"/"+tc.name, func(t *testing.T) {
				stdinIsTerminal = func() bool { return tc.tty }
				if got := startArgv(t, tc.args...); got != string(want) {
					t.Fatalf("argv drifted\n--- got ---\n%s--- want ---\n%s", got, want)
				}
			})
		}
	}
}
