#!/usr/bin/env bash
# Purpose: environments.sh — env-aware operations and promotion workflows.
#
# Subcommands:
#   yakos env status                    # current branch → env mapping
#   yakos env promote <from> <to>       # PR from env's branch → to env's branch
#   yakos env validate                  # check .yakos.yml environments section
#   yakos env list                      # list configured envs
#
# Pluggable PR tool: detects gh, glab, or falls back to plain git + URL.

set -eu

: "${YAKOS_LIB:?environments.sh: YAKOS_LIB must be set}"
. "$YAKOS_LIB/compat.sh"
. "$YAKOS_LIB/project-config.sh"

_env_project_dir() {
    # Resolve project repo dir. Read from agent-control or env var.
    if [ -n "${YAKOS_PROJECT_DIR:-}" ]; then
        printf '%s\n' "$YAKOS_PROJECT_DIR"
        return
    fi
    if [ -f "$PWD/.yakos.yml" ]; then
        printf '%s\n' "$PWD"; return
    fi
    if [ -f "$PWD/.project-path" ]; then
        cat "$PWD/.project-path"; return
    fi
    ct_die "could not resolve project dir"
}

_env_current_branch() {
    git -C "$(_env_project_dir)" rev-parse --abbrev-ref HEAD 2>/dev/null
}

_env_branch_for() {
    # Get the branch name configured for a given env.
    local env_name="$1" project
    project="$(_env_project_dir)"
    yk_pcfg_get "$project" "environments.$env_name.branch"
}

_env_for_branch() {
    # Reverse: given current branch, return matching env name (or empty).
    local branch="$1" project
    project="$(_env_project_dir)"
    # TODO(M5): read all environments from .yakos.yml. For draft,
    # check the three standard env names.
    for env_name in dev test prod; do
        local b
        b="$(_env_branch_for "$env_name")"
        if [ "$b" = "$branch" ]; then
            printf '%s\n' "$env_name"
            return
        fi
    done
}

_env_detect_pr_tool() {
    # Pluggable PR tool detection.
    if command -v gh >/dev/null 2>&1; then printf 'gh\n'; return; fi
    if command -v glab >/dev/null 2>&1; then printf 'glab\n'; return; fi
    printf 'git\n'  # plain git push + URL guess
}

cmd_status() {
    local project branch env_name
    project="$(_env_project_dir)"
    branch="$(_env_current_branch)"
    env_name="$(_env_for_branch "$branch")"

    cat <<EOF
Project: $project
Current branch: $branch
Mapped environment: ${env_name:-<none>}
PR tool detected: $(_env_detect_pr_tool)
EOF
}

cmd_validate() {
    local project file
    project="$(_env_project_dir)"
    file="$project/.yakos.yml"
    [ -f "$file" ] || ct_die "no .yakos.yml at $file"

    # Check that environments section exists.
    local env_count
    env_count="$(grep -cE '^  [a-z]+:$' "$file" 2>/dev/null || echo 0)"
    if [ "$env_count" = "0" ]; then
        echo "  [info] no environments declared in .yakos.yml"
        return 0
    fi

    echo "  [ok] environments section present"
    # Check each env has a branch.
    for env_name in dev test prod; do
        local b
        b="$(_env_branch_for "$env_name" 2>/dev/null)"
        if [ -n "$b" ]; then
            echo "  [ok] $env_name → branch '$b'"
            # Check the branch actually exists.
            if ! git -C "$project" rev-parse --verify "$b" >/dev/null 2>&1; then
                echo "  [warn] $env_name branch '$b' does not exist locally"
            fi
        else
            echo "  [info] $env_name not configured"
        fi
    done
}

cmd_list() {
    local project
    project="$(_env_project_dir)"
    for env_name in dev test prod; do
        local b
        b="$(_env_branch_for "$env_name" 2>/dev/null)"
        [ -n "$b" ] && printf '  %s → %s\n' "$env_name" "$b"
    done
}

cmd_promote() {
    local from="$1" to="$2"
    local project from_branch to_branch tool
    project="$(_env_project_dir)"
    from_branch="$(_env_branch_for "$from")"
    to_branch="$(_env_branch_for "$to")"

    [ -n "$from_branch" ] || ct_die "no branch configured for env '$from'"
    [ -n "$to_branch" ]   || ct_die "no branch configured for env '$to'"

    # Confirm from-branch is up to date locally.
    git -C "$project" fetch origin "$from_branch" 2>/dev/null || true
    local local_head remote_head
    local_head="$(git -C "$project" rev-parse "$from_branch")"
    remote_head="$(git -C "$project" rev-parse "origin/$from_branch" 2>/dev/null || echo 'none')"
    if [ "$local_head" != "$remote_head" ]; then
        ct_log "WARN: local $from_branch ($local_head) differs from origin ($remote_head)"
        ct_log "Push $from_branch first, then re-run promote."
        exit 1
    fi

    tool="$(_env_detect_pr_tool)"
    local title body
    title="chore($to): promote $from_branch → $to_branch at $(ct_iso_now_z)"
    body="$(cat <<EOF
Promotion: $from_branch → $to_branch

Generated by yakos env promote $from $to at $(ct_iso_now_z).

Changelog since last $to promotion:
$(git -C "$project" log --oneline "$to_branch..$from_branch" 2>/dev/null || echo "(no commits)")
EOF
)"

    case "$tool" in
        gh)
            cd "$project"
            gh pr create --base "$to_branch" --head "$from_branch" \
                --title "$title" --body "$body"
            ;;
        glab)
            cd "$project"
            glab mr create --target-branch "$to_branch" --source-branch "$from_branch" \
                --title "$title" --description "$body"
            ;;
        git|*)
            ct_log "No gh/glab detected. Open the PR manually:"
            ct_log "  base: $to_branch"
            ct_log "  head: $from_branch"
            ct_log "  title: $title"
            ct_log ""
            ct_log "Suggested commands (if your remote is github):"
            ct_log "  git push origin $from_branch"
            ct_log "  open https://github.com/<owner>/<repo>/compare/$to_branch...$from_branch"
            ;;
    esac
}

case "${1:-help}" in
    status)   shift; cmd_status "$@" ;;
    promote)  shift; cmd_promote "$@" ;;
    validate) shift; cmd_validate "$@" ;;
    list)     shift; cmd_list "$@" ;;
    help|--help|-h)
        cat <<EOF
yakos env — dev/test/prod environment management

  yakos env status                  # current branch → env
  yakos env promote <from> <to>     # PR <from>'s branch → <to>'s branch
  yakos env validate                # check .yakos.yml environments
  yakos env list                    # list configured envs

Config lives in .yakos.yml under \`environments:\`.
See lib/rules/environment-discipline.md.
EOF
        ;;
    *) ct_die "yakos env: unknown subcommand '$1'" ;;
esac
