#!/usr/bin/env bash
# Purpose: Manage YakOS git hooks for the current project repo.
#   Subcommands: install | uninstall | status.
#   Installs the pre-push version gate into <repo>/.git/hooks/pre-push
#   (with a .framework-hash sibling so doctor can detect drift).
# Inputs:  $1 subcommand; --force to overwrite an existing hook.
# Outputs: stdout: human-readable status; stderr: errors.
# Reads:   $YAKOS_ROOT/lib/hooks/git/pre-push-version-gate.sh
# Writes:  <repo>/.git/hooks/pre-push and .framework-hash sibling.
# Exit codes: 0 success, 2 user error, 3 git/repo error, 4 file error.

set -eu

: "${YAKOS_ROOT:?YAKOS_ROOT must be set; run via 'yakos git-hooks'}"
: "${YAKOS_LIB:?YAKOS_LIB must be set; run via 'yakos git-hooks'}"
# shellcheck source=./compat.sh
. "$YAKOS_LIB/compat.sh"

usage() {
    cat <<'EOF'
yakos git-hooks {install|uninstall|status} [--force]

Manage YakOS git hooks for the current project repo.

  install                  Install the pre-push version gate.
  install --promotion-gate Install version-gate + promotion-gate composed
                           pre-push (Plan 3 M5 / v0.17+). Promotion gate
                           refuses pushes that violate dev→test→prod order
                           when .yakos.yml declares environments.
  uninstall                Remove the pre-push hook IFF it's YakOS-owned
                           (verified by .framework-hash sibling).
  status                   Report whether the gate is installed + drift state.

Hooks honor YAKOS_GATE_DISABLE=1 / YAKOS_PROMOTION_OVERRIDE=1 (bypass + log)
and `git push --no-verify`. See lib/hooks/git/README.md for the contract.
EOF
}

GATE_SRC="$YAKOS_ROOT/lib/hooks/git/pre-push-version-gate.sh"
PROMOTION_GATE_SRC="$YAKOS_ROOT/lib/hooks/git/pre-push-promotion-gate.sh"

require_repo() {
    if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        ct_die "not inside a git repo (run from a project)"
    fi
    REPO_ROOT="$(git rev-parse --show-toplevel)"
    HOOK_DIR="$REPO_ROOT/.git/hooks"
}

cmd_install() {
    local force=0
    local with_promotion=0
    for arg in "$@"; do
        case "$arg" in
            --force) force=1 ;;
            --promotion-gate) with_promotion=1 ;;
            *) ct_die "install: unknown arg: $arg" ;;
        esac
    done
    require_repo
    [ -f "$GATE_SRC" ] || ct_die "gate source not found: $GATE_SRC"
    if [ "$with_promotion" = "1" ]; then
        [ -f "$PROMOTION_GATE_SRC" ] || ct_die "promotion gate source not found: $PROMOTION_GATE_SRC"
    fi
    mkdir -p "$HOOK_DIR"
    local dst="$HOOK_DIR/pre-push"
    local hash_sibling="${dst}.framework-hash"

    # Compute the source hash. For composed install (--promotion-gate), the
    # "framework hash" is the concat of both gate hashes so drift detection
    # catches changes to either.
    local src_hash
    if [ "$with_promotion" = "1" ]; then
        src_hash="$(printf '%s|%s' "$(ct_sha256 "$GATE_SRC")" "$(ct_sha256 "$PROMOTION_GATE_SRC")")"
    else
        src_hash="$(ct_sha256 "$GATE_SRC")"
    fi

    if [ -e "$dst" ] && [ "$force" != "1" ]; then
        if [ -f "$hash_sibling" ]; then
            local existing_hash
            existing_hash="$(cat "$hash_sibling" 2>/dev/null || echo "")"
            if [ "$src_hash" = "$existing_hash" ]; then
                ct_log "pre-push gate already installed at $dst (current version); nothing to do"
                return 0
            else
                ct_die "pre-push hook is YakOS-owned but stale or composition changed (rerun with --force to refresh)"
            fi
        fi
        ct_die "pre-push hook exists at $dst and isn't YakOS-owned (rerun with --force to overwrite — destructive)"
    fi

    if [ "$with_promotion" = "1" ]; then
        # Composed pre-push: tee stdin to both gates; exit non-zero on any refusal.
        cat > "$dst" <<COMPOSED
#!/usr/bin/env bash
# YakOS composed pre-push: version gate + promotion gate.
# Generated by yakos git-hooks install --promotion-gate.
set -eu
stdin_buf="\$(cat)"
rc=0
printf '%s' "\$stdin_buf" | "$GATE_SRC" "\$@" || rc=\$?
[ "\$rc" -eq 0 ] || exit "\$rc"
printf '%s' "\$stdin_buf" | "$PROMOTION_GATE_SRC" "\$@" || rc=\$?
exit "\$rc"
COMPOSED
        chmod +x "$dst"
        printf '%s\n' "$src_hash" > "$hash_sibling"
        ct_log "pre-push (version-gate + promotion-gate) installed at $dst"
        ct_log "  override version-gate:   YAKOS_GATE_DISABLE=1 git push"
        ct_log "  override promotion-gate: YAKOS_PROMOTION_OVERRIDE=1 git push"
        ct_log "  both logged to ~/.yakos-state/gate-log.ndjson"
    else
        cp "$GATE_SRC" "$dst"
        chmod +x "$dst"
        printf '%s\n' "$src_hash" > "$hash_sibling"
        ct_log "pre-push gate installed at $dst"
        ct_log "  to override: YAKOS_GATE_DISABLE=1 git push   (logged to ~/.yakos-state/gate-log.ndjson)"
    fi
    ct_log "  to remove:   yakos git-hooks uninstall"
}

cmd_uninstall() {
    require_repo
    local dst="$HOOK_DIR/pre-push"
    local hash_sibling="${dst}.framework-hash"
    if [ ! -e "$dst" ]; then
        ct_log "pre-push hook not present at $dst; nothing to remove"
        return 0
    fi
    if [ ! -f "$hash_sibling" ]; then
        ct_die "pre-push hook at $dst isn't YakOS-owned (no .framework-hash); refusing to remove"
    fi
    rm -f "$dst" "$hash_sibling"
    ct_log "pre-push gate removed from $dst"
}

cmd_status() {
    require_repo
    local dst="$HOOK_DIR/pre-push"
    local hash_sibling="${dst}.framework-hash"
    if [ ! -e "$dst" ]; then
        printf '%s\n' "pre-push gate: NOT INSTALLED"
        printf '%s\n' "  install: yakos git-hooks install"
        return 0
    fi
    if [ ! -f "$hash_sibling" ]; then
        printf '%s\n' "pre-push gate: PRESENT but not YakOS-owned (no .framework-hash sibling)"
        return 0
    fi
    local current_hash existing_hash
    current_hash="$(ct_sha256 "$GATE_SRC")"
    existing_hash="$(cat "$hash_sibling" 2>/dev/null || echo "")"
    if [ "$current_hash" = "$existing_hash" ]; then
        printf '%s\n' "pre-push gate: INSTALLED (current version, no drift)"
    else
        printf '%s\n' "pre-push gate: INSTALLED but DRIFTED from framework"
        printf '%s\n' "  framework hash: $current_hash"
        printf '%s\n' "  installed hash: $existing_hash"
        printf '%s\n' "  to refresh: yakos git-hooks install --force"
    fi
}

cmd="${1:-}"
shift || true
case "$cmd" in
    install)   cmd_install "$@" ;;
    uninstall) cmd_uninstall "$@" ;;
    status)    cmd_status "$@" ;;
    -h|--help|"") usage ;;
    *) usage >&2; exit 2 ;;
esac
