// Code generated by protoc-gen-go. DO NOT EDIT.
// Hand-written stand-in: protoc not available in CI; see yakos.proto for
// source of truth. Regenerate when protoc is available.
//
// source: proto/yakos/v1/yakos.proto

// Package yakosv1 contains generated protobuf types for the yakOS gRPC API.
package yakosv1

// ---- Dispatch ---------------------------------------------------------------

// DispatchRunRequest is the request for Dispatch.Run and Dispatch.Stream.
// Proto field numbers 1-7 are stable; identity fields use 8-10 (never renumber).
type DispatchRunRequest struct {
	Agent     string `json:"agent,omitempty"`      // field 1
	Task      string `json:"task,omitempty"`       // field 2
	Project   string `json:"project,omitempty"`    // field 3
	Runtime   string `json:"runtime,omitempty"`    // field 4
	Model     string `json:"model,omitempty"`      // field 5
	YakosRoot string `json:"yakos_root,omitempty"` // field 6
	Timeout   int32  `json:"timeout,omitempty"`    // field 7
	// Phase 2 identity fields (fields 8-10 — additive, never renumber).
	OperatorID     string `json:"operator_id,omitempty"`     // field 8
	ConversationID string `json:"conversation_id,omitempty"` // field 9
	SessionID      string `json:"session_id,omitempty"`      // field 10
}

// DispatchRunResponse is the result of Dispatch.Run.
type DispatchRunResponse struct {
	ExitCode      int32   `json:"exit_code,omitempty"`
	DurationS     float64 `json:"duration_s,omitempty"`
	OutputBytes   int64   `json:"output_bytes,omitempty"`
	ModelResolved string  `json:"model_resolved,omitempty"`
}

// DispatchStreamChunk is one chunk in the Dispatch.Stream server stream.
// Type is "token" for incremental output or "summary" for the final record.
type DispatchStreamChunk struct {
	Type          string  `json:"type,omitempty"`
	Text          string  `json:"text,omitempty"`
	ExitCode      int32   `json:"exit_code,omitempty"`
	DurationS     float64 `json:"duration_s,omitempty"`
	OutputBytes   int64   `json:"output_bytes,omitempty"`
	ModelResolved string  `json:"model_resolved,omitempty"`
}

// ---- Kanban -----------------------------------------------------------------

// KanbanListRequest is the request for Kanban.List.
type KanbanListRequest struct {
	Column string `json:"column,omitempty"`
	Limit  int32  `json:"limit,omitempty"`
}

// KanbanItem is one task on the board.
type KanbanItem struct {
	Id     string `json:"id,omitempty"`
	Title  string `json:"title,omitempty"`
	Column string `json:"column,omitempty"`
}

// KanbanListResponse is the result of Kanban.List.
type KanbanListResponse struct {
	Items []*KanbanItem `json:"items"`
}

// KanbanAddRequest is the request for Kanban.Add.
type KanbanAddRequest struct {
	Title    string `json:"title,omitempty"`
	Category string `json:"category,omitempty"`
	Notes    string `json:"notes,omitempty"`
}

// KanbanAddResponse is the result of Kanban.Add.
type KanbanAddResponse struct {
	Id string `json:"id,omitempty"`
}

// KanbanMoveRequest is the request for Kanban.Move.
type KanbanMoveRequest struct {
	Id string `json:"id,omitempty"`
	To string `json:"to,omitempty"`
}

// KanbanMoveResponse is the result of Kanban.Move.
type KanbanMoveResponse struct {
	Ok bool `json:"ok,omitempty"`
}

// KanbanDoneRequest is the request for Kanban.Done.
type KanbanDoneRequest struct {
	Id string `json:"id,omitempty"`
}

// KanbanDoneResponse is the result of Kanban.Done.
type KanbanDoneResponse struct {
	Ok bool `json:"ok,omitempty"`
}

// KanbanWatchRequest is the request for Kanban.Watch.
type KanbanWatchRequest struct{}

// KanbanEvent is one event in the Kanban.Watch server stream.
type KanbanEvent struct {
	Op    string `json:"op,omitempty"`
	Id    string `json:"id,omitempty"`
	From  string `json:"from,omitempty"`
	To    string `json:"to,omitempty"`
	Title string `json:"title,omitempty"`
}

// ---- Cost -------------------------------------------------------------------

// CostAggregateRequest is the request for Cost.Aggregate.
type CostAggregateRequest struct {
	By    string `json:"by,omitempty"`
	Since string `json:"since,omitempty"`
	Limit int32  `json:"limit,omitempty"`
}

// CostRow is one row in a cost aggregate report.
type CostRow struct {
	Key        string  `json:"key,omitempty"`
	Dispatches int64   `json:"dispatches,omitempty"`
	TotalS     float64 `json:"total_s,omitempty"`
}

// CostAggregateResponse is the result of Cost.Aggregate.
type CostAggregateResponse struct {
	By   string     `json:"by,omitempty"`
	Rows []*CostRow `json:"rows"`
}

// ---- Status -----------------------------------------------------------------

// StatusReadRequest is the request for Status.Read.
type StatusReadRequest struct {
	Project string `json:"project,omitempty"`
}

// StatusReadResponse is the result of Status.Read.
type StatusReadResponse struct {
	Project   string `json:"project,omitempty"`
	Phase     string `json:"phase,omitempty"`
	Summary   string `json:"summary,omitempty"`
	TodoCount int32  `json:"todo_count,omitempty"`
	DoneCount int32  `json:"done_count,omitempty"`
}

// ---- Refresh ----------------------------------------------------------------

// RefreshRunRequest is the request for Refresh.Run.
type RefreshRunRequest struct {
	DryRun bool `json:"dry_run,omitempty"`
}

// RefreshRunResponse is the result of Refresh.Run.
type RefreshRunResponse struct {
	Output string `json:"output,omitempty"`
}
