// Code generated by protoc-gen-go. DO NOT EDIT.
// Hand-written stand-in: protoc not available in CI; see yakos.proto for
// source of truth. Regenerate when protoc is available.
//
// source: proto/yakos/v1/yakos.proto

// Package yakosv1 contains generated protobuf types for the yakOS gRPC API.
package yakosv1

// ---- Dispatch ---------------------------------------------------------------

// DispatchRunRequest is the request for Dispatch.Run and Dispatch.Stream.
// Proto field numbers 1-7 are stable; identity fields use 8-10 (never renumber).
type DispatchRunRequest struct {
	Agent     string `json:"agent,omitempty"`      // field 1
	Task      string `json:"task,omitempty"`       // field 2
	Project   string `json:"project,omitempty"`    // field 3
	Runtime   string `json:"runtime,omitempty"`    // field 4
	Model     string `json:"model,omitempty"`      // field 5
	YakosRoot string `json:"yakos_root,omitempty"` // field 6
	Timeout   int32  `json:"timeout,omitempty"`    // field 7
	// Phase 2 identity fields (fields 8-10 — additive, never renumber).
	OperatorID     string `json:"operator_id,omitempty"`     // field 8
	ConversationID string `json:"conversation_id,omitempty"` // field 9
	SessionID      string `json:"session_id,omitempty"`      // field 10
}

// DispatchRunResponse is the result of Dispatch.Run.
type DispatchRunResponse struct {
	ExitCode      int32   `json:"exit_code,omitempty"`
	DurationS     float64 `json:"duration_s,omitempty"`
	OutputBytes   int64   `json:"output_bytes,omitempty"`
	ModelResolved string  `json:"model_resolved,omitempty"`
}

// DispatchStreamChunk is one chunk in the Dispatch.Stream server stream.
// Type is "token" for incremental output or "summary" for the final record.
type DispatchStreamChunk struct {
	Type          string  `json:"type,omitempty"`
	Text          string  `json:"text,omitempty"`
	ExitCode      int32   `json:"exit_code,omitempty"`
	DurationS     float64 `json:"duration_s,omitempty"`
	OutputBytes   int64   `json:"output_bytes,omitempty"`
	ModelResolved string  `json:"model_resolved,omitempty"`
}

// ---- Kanban -----------------------------------------------------------------

// KanbanListRequest is the request for Kanban.List.
type KanbanListRequest struct {
	Column string `json:"column,omitempty"`
	Limit  int32  `json:"limit,omitempty"`
}

// KanbanItem is one task on the board.
type KanbanItem struct {
	Id     string `json:"id,omitempty"`
	Title  string `json:"title,omitempty"`
	Column string `json:"column,omitempty"`
}

// KanbanListResponse is the result of Kanban.List.
type KanbanListResponse struct {
	Items []*KanbanItem `json:"items"`
}

// KanbanAddRequest is the request for Kanban.Add.
type KanbanAddRequest struct {
	Title    string `json:"title,omitempty"`
	Category string `json:"category,omitempty"`
	Notes    string `json:"notes,omitempty"`
}

// KanbanAddResponse is the result of Kanban.Add.
type KanbanAddResponse struct {
	Id string `json:"id,omitempty"`
}

// KanbanMoveRequest is the request for Kanban.Move.
type KanbanMoveRequest struct {
	Id string `json:"id,omitempty"`
	To string `json:"to,omitempty"`
}

// KanbanMoveResponse is the result of Kanban.Move.
type KanbanMoveResponse struct {
	Ok bool `json:"ok,omitempty"`
}

// KanbanDoneRequest is the request for Kanban.Done.
type KanbanDoneRequest struct {
	Id string `json:"id,omitempty"`
}

// KanbanDoneResponse is the result of Kanban.Done.
type KanbanDoneResponse struct {
	Ok bool `json:"ok,omitempty"`
}

// KanbanWatchRequest is the request for Kanban.Watch.
type KanbanWatchRequest struct{}

// KanbanEvent is one event in the Kanban.Watch server stream.
type KanbanEvent struct {
	Op    string `json:"op,omitempty"`
	Id    string `json:"id,omitempty"`
	From  string `json:"from,omitempty"`
	To    string `json:"to,omitempty"`
	Title string `json:"title,omitempty"`
}

// ---- Cost -------------------------------------------------------------------

// CostAggregateRequest is the request for Cost.Aggregate.
type CostAggregateRequest struct {
	By    string `json:"by,omitempty"`
	Since string `json:"since,omitempty"`
	Limit int32  `json:"limit,omitempty"`
}

// CostRow is one row in a cost aggregate report.
type CostRow struct {
	Key        string  `json:"key,omitempty"`
	Dispatches int64   `json:"dispatches,omitempty"`
	TotalS     float64 `json:"total_s,omitempty"`
}

// CostAggregateResponse is the result of Cost.Aggregate.
type CostAggregateResponse struct {
	By   string     `json:"by,omitempty"`
	Rows []*CostRow `json:"rows"`
}

// ---- Status -----------------------------------------------------------------

// StatusReadRequest is the request for Status.Read.
type StatusReadRequest struct {
	Project string `json:"project,omitempty"`
}

// StatusReadResponse is the result of Status.Read.
type StatusReadResponse struct {
	Project   string `json:"project,omitempty"`
	Phase     string `json:"phase,omitempty"`
	Summary   string `json:"summary,omitempty"`
	TodoCount int32  `json:"todo_count,omitempty"`
	DoneCount int32  `json:"done_count,omitempty"`
}

// ---- Refresh ----------------------------------------------------------------

// RefreshRunRequest is the request for Refresh.Run.
//
// SECURITY (round-2 review R5, M2 follow-up, security-review-2026-09-14.md):
// this field used to be named DryRun (proto field dry_run, field number 1).
// A proto3 scalar bool has no wire-presence bit, so "omitted" and "false"
// are indistinguishable — the zero value (false) meant APPLY, so an
// entirely omitted request already wrote hook scripts, settings.json, and
// agent symlinks across every project under $HOME/agent-control. Renamed to
// Apply (destructive = true, explicit) so the zero value is safe by
// construction, with no default state left that means write.
//
// Field number 1 (dry_run) is retired, not reused (round-2 review N9): under
// a real protobuf wire codec, reusing number 1 with inverted semantics would
// let an old client's explicit, safe `dry_run = true` decode as
// `apply = true` and write. This JSON codec (internal/grpcserver) keys on
// field name, not number, so the collision is not reachable today — but the
// .proto is the published contract for any future real-protobuf client, so
// it reserves 1 and "dry_run" and assigns Apply field number 3. Hand-edited
// to match proto/yakos/v1/yakos.proto; see that file's header for why this
// .pb.go is hand-maintained rather than protoc-generated.
type RefreshRunRequest struct {
	Apply bool `json:"apply,omitempty"` // field 3 (dry_run/field 1 retired, see above)
	// Scope selects how many projects a write reaches. "" (default) or
	// "project" limits repair to the server-configured WorkspaceRoot only;
	// "all" reaches every project under $HOME/agent-control — a much
	// larger blast radius that must be requested explicitly (R19).
	Scope string `json:"scope,omitempty"` // field 2
}

// RefreshRunResponse is the result of Refresh.Run.
type RefreshRunResponse struct {
	Output string `json:"output,omitempty"`
}

// ---- Version ------------------------------------------------------------

// VersionRequest is the request for Version.Get. It carries no fields.
type VersionRequest struct{}

// VersionResponse is the result of Version.Get — the CLI↔daemon build
// handshake. Shares its field shape with the JSON-RPC yakos.version method
// and REST GET /v1/version; see internal/daemonclient.VersionInfo and
// internal/buildinfo.
type VersionResponse struct {
	Version string `json:"version,omitempty"`
	Commit  string `json:"commit,omitempty"`
	LibHash string `json:"lib_hash,omitempty"`
	BuildID string `json:"build_id,omitempty"`
}
