// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// Hand-written stand-in: protoc not available in CI; see yakos.proto for
// source of truth. Regenerate when protoc is available.
//
// source: proto/yakos/v1/yakos.proto

package yakosv1

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// ---- Dispatch service -------------------------------------------------------

// DispatchClient is the client API for the Dispatch service.
type DispatchClient interface {
	Run(ctx context.Context, in *DispatchRunRequest, opts ...grpc.CallOption) (*DispatchRunResponse, error)
	Stream(ctx context.Context, in *DispatchRunRequest, opts ...grpc.CallOption) (Dispatch_StreamClient, error)
}

type dispatchClient struct {
	cc grpc.ClientConnInterface
}

func NewDispatchClient(cc grpc.ClientConnInterface) DispatchClient {
	return &dispatchClient{cc}
}

func (c *dispatchClient) Run(ctx context.Context, in *DispatchRunRequest, opts ...grpc.CallOption) (*DispatchRunResponse, error) {
	out := new(DispatchRunResponse)
	err := c.cc.Invoke(ctx, "/yakos.v1.Dispatch/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchClient) Stream(ctx context.Context, in *DispatchRunRequest, opts ...grpc.CallOption) (Dispatch_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Dispatch_ServiceDesc.Streams[0], "/yakos.v1.Dispatch/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &dispatchStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// Dispatch_StreamClient is the client-side stream for Dispatch.Stream.
type Dispatch_StreamClient interface {
	Recv() (*DispatchStreamChunk, error)
	grpc.ClientStream
}

type dispatchStreamClient struct {
	grpc.ClientStream
}

func (x *dispatchStreamClient) Recv() (*DispatchStreamChunk, error) {
	m := new(DispatchStreamChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DispatchServer is the server API for the Dispatch service.
type DispatchServer interface {
	Run(context.Context, *DispatchRunRequest) (*DispatchRunResponse, error)
	Stream(*DispatchRunRequest, Dispatch_StreamServer) error
	mustEmbedUnimplementedDispatchServer()
}

// UnimplementedDispatchServer must be embedded to have forward-compatible implementations.
type UnimplementedDispatchServer struct{}

func (UnimplementedDispatchServer) Run(context.Context, *DispatchRunRequest) (*DispatchRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedDispatchServer) Stream(*DispatchRunRequest, Dispatch_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedDispatchServer) mustEmbedUnimplementedDispatchServer() {}

// Dispatch_StreamServer is the server-side stream for Dispatch.Stream.
type Dispatch_StreamServer interface {
	Send(*DispatchStreamChunk) error
	grpc.ServerStream
}

type dispatchStreamServer struct {
	grpc.ServerStream
}

func (x *dispatchStreamServer) Send(m *DispatchStreamChunk) error {
	return x.ServerStream.SendMsg(m)
}

// RegisterDispatchServer registers the server implementation.
func RegisterDispatchServer(s grpc.ServiceRegistrar, srv DispatchServer) {
	s.RegisterService(&Dispatch_ServiceDesc, srv)
}

// Dispatch_ServiceDesc is the grpc.ServiceDesc for the Dispatch service.
var Dispatch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yakos.v1.Dispatch",
	HandlerType: (*DispatchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _Dispatch_Run_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Dispatch_Stream_Handler,
			ServerStreams: true,
		},
	},
}

func _Dispatch_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/yakos.v1.Dispatch/Run"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServer).Run(ctx, req.(*DispatchRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dispatch_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DispatchRunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DispatchServer).Stream(m, &dispatchStreamServer{stream})
}

// ---- Kanban service ---------------------------------------------------------

// KanbanClient is the client API for the Kanban service.
type KanbanClient interface {
	List(ctx context.Context, in *KanbanListRequest, opts ...grpc.CallOption) (*KanbanListResponse, error)
	Add(ctx context.Context, in *KanbanAddRequest, opts ...grpc.CallOption) (*KanbanAddResponse, error)
	Move(ctx context.Context, in *KanbanMoveRequest, opts ...grpc.CallOption) (*KanbanMoveResponse, error)
	Done(ctx context.Context, in *KanbanDoneRequest, opts ...grpc.CallOption) (*KanbanDoneResponse, error)
	Watch(ctx context.Context, in *KanbanWatchRequest, opts ...grpc.CallOption) (Kanban_WatchClient, error)
}

type kanbanClient struct {
	cc grpc.ClientConnInterface
}

func NewKanbanClient(cc grpc.ClientConnInterface) KanbanClient {
	return &kanbanClient{cc}
}

func (c *kanbanClient) List(ctx context.Context, in *KanbanListRequest, opts ...grpc.CallOption) (*KanbanListResponse, error) {
	out := new(KanbanListResponse)
	err := c.cc.Invoke(ctx, "/yakos.v1.Kanban/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kanbanClient) Add(ctx context.Context, in *KanbanAddRequest, opts ...grpc.CallOption) (*KanbanAddResponse, error) {
	out := new(KanbanAddResponse)
	err := c.cc.Invoke(ctx, "/yakos.v1.Kanban/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kanbanClient) Move(ctx context.Context, in *KanbanMoveRequest, opts ...grpc.CallOption) (*KanbanMoveResponse, error) {
	out := new(KanbanMoveResponse)
	err := c.cc.Invoke(ctx, "/yakos.v1.Kanban/Move", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kanbanClient) Done(ctx context.Context, in *KanbanDoneRequest, opts ...grpc.CallOption) (*KanbanDoneResponse, error) {
	out := new(KanbanDoneResponse)
	err := c.cc.Invoke(ctx, "/yakos.v1.Kanban/Done", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kanbanClient) Watch(ctx context.Context, in *KanbanWatchRequest, opts ...grpc.CallOption) (Kanban_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &Kanban_ServiceDesc.Streams[0], "/yakos.v1.Kanban/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &kanbanWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// Kanban_WatchClient is the client-side stream for Kanban.Watch.
type Kanban_WatchClient interface {
	Recv() (*KanbanEvent, error)
	grpc.ClientStream
}

type kanbanWatchClient struct {
	grpc.ClientStream
}

func (x *kanbanWatchClient) Recv() (*KanbanEvent, error) {
	m := new(KanbanEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KanbanServer is the server API for the Kanban service.
type KanbanServer interface {
	List(context.Context, *KanbanListRequest) (*KanbanListResponse, error)
	Add(context.Context, *KanbanAddRequest) (*KanbanAddResponse, error)
	Move(context.Context, *KanbanMoveRequest) (*KanbanMoveResponse, error)
	Done(context.Context, *KanbanDoneRequest) (*KanbanDoneResponse, error)
	Watch(*KanbanWatchRequest, Kanban_WatchServer) error
	mustEmbedUnimplementedKanbanServer()
}

// UnimplementedKanbanServer must be embedded to have forward-compatible implementations.
type UnimplementedKanbanServer struct{}

func (UnimplementedKanbanServer) List(context.Context, *KanbanListRequest) (*KanbanListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedKanbanServer) Add(context.Context, *KanbanAddRequest) (*KanbanAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedKanbanServer) Move(context.Context, *KanbanMoveRequest) (*KanbanMoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Move not implemented")
}
func (UnimplementedKanbanServer) Done(context.Context, *KanbanDoneRequest) (*KanbanDoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Done not implemented")
}
func (UnimplementedKanbanServer) Watch(*KanbanWatchRequest, Kanban_WatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedKanbanServer) mustEmbedUnimplementedKanbanServer() {}

// Kanban_WatchServer is the server-side stream for Kanban.Watch.
type Kanban_WatchServer interface {
	Send(*KanbanEvent) error
	grpc.ServerStream
}

type kanbanWatchServer struct {
	grpc.ServerStream
}

func (x *kanbanWatchServer) Send(m *KanbanEvent) error {
	return x.ServerStream.SendMsg(m)
}

// RegisterKanbanServer registers the server implementation.
func RegisterKanbanServer(s grpc.ServiceRegistrar, srv KanbanServer) {
	s.RegisterService(&Kanban_ServiceDesc, srv)
}

// Kanban_ServiceDesc is the grpc.ServiceDesc for the Kanban service.
var Kanban_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yakos.v1.Kanban",
	HandlerType: (*KanbanServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "List", Handler: _Kanban_List_Handler},
		{MethodName: "Add", Handler: _Kanban_Add_Handler},
		{MethodName: "Move", Handler: _Kanban_Move_Handler},
		{MethodName: "Done", Handler: _Kanban_Done_Handler},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Kanban_Watch_Handler,
			ServerStreams: true,
		},
	},
}

func _Kanban_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KanbanListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KanbanServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/yakos.v1.Kanban/List"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KanbanServer).List(ctx, req.(*KanbanListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kanban_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KanbanAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KanbanServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/yakos.v1.Kanban/Add"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KanbanServer).Add(ctx, req.(*KanbanAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kanban_Move_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KanbanMoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KanbanServer).Move(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/yakos.v1.Kanban/Move"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KanbanServer).Move(ctx, req.(*KanbanMoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kanban_Done_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KanbanDoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KanbanServer).Done(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/yakos.v1.Kanban/Done"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KanbanServer).Done(ctx, req.(*KanbanDoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kanban_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(KanbanWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KanbanServer).Watch(m, &kanbanWatchServer{stream})
}

// ---- Cost service -----------------------------------------------------------

// CostClient is the client API for the Cost service.
type CostClient interface {
	Aggregate(ctx context.Context, in *CostAggregateRequest, opts ...grpc.CallOption) (*CostAggregateResponse, error)
}

type costClient struct {
	cc grpc.ClientConnInterface
}

func NewCostClient(cc grpc.ClientConnInterface) CostClient {
	return &costClient{cc}
}

func (c *costClient) Aggregate(ctx context.Context, in *CostAggregateRequest, opts ...grpc.CallOption) (*CostAggregateResponse, error) {
	out := new(CostAggregateResponse)
	err := c.cc.Invoke(ctx, "/yakos.v1.Cost/Aggregate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CostServer is the server API for the Cost service.
type CostServer interface {
	Aggregate(context.Context, *CostAggregateRequest) (*CostAggregateResponse, error)
	mustEmbedUnimplementedCostServer()
}

// UnimplementedCostServer must be embedded to have forward-compatible implementations.
type UnimplementedCostServer struct{}

func (UnimplementedCostServer) Aggregate(context.Context, *CostAggregateRequest) (*CostAggregateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Aggregate not implemented")
}
func (UnimplementedCostServer) mustEmbedUnimplementedCostServer() {}

// RegisterCostServer registers the server implementation.
func RegisterCostServer(s grpc.ServiceRegistrar, srv CostServer) {
	s.RegisterService(&Cost_ServiceDesc, srv)
}

// Cost_ServiceDesc is the grpc.ServiceDesc for the Cost service.
var Cost_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yakos.v1.Cost",
	HandlerType: (*CostServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "Aggregate", Handler: _Cost_Aggregate_Handler},
	},
	Streams: []grpc.StreamDesc{},
}

func _Cost_Aggregate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CostAggregateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CostServer).Aggregate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/yakos.v1.Cost/Aggregate"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CostServer).Aggregate(ctx, req.(*CostAggregateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ---- Status service ---------------------------------------------------------

// StatusClient is the client API for the Status service.
type StatusClient interface {
	Read(ctx context.Context, in *StatusReadRequest, opts ...grpc.CallOption) (*StatusReadResponse, error)
}

type statusClient struct {
	cc grpc.ClientConnInterface
}

func NewStatusClient(cc grpc.ClientConnInterface) StatusClient {
	return &statusClient{cc}
}

func (c *statusClient) Read(ctx context.Context, in *StatusReadRequest, opts ...grpc.CallOption) (*StatusReadResponse, error) {
	out := new(StatusReadResponse)
	err := c.cc.Invoke(ctx, "/yakos.v1.Status/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatusServer is the server API for the Status service.
type StatusServer interface {
	Read(context.Context, *StatusReadRequest) (*StatusReadResponse, error)
	mustEmbedUnimplementedStatusServer()
}

// UnimplementedStatusServer must be embedded to have forward-compatible implementations.
type UnimplementedStatusServer struct{}

func (UnimplementedStatusServer) Read(context.Context, *StatusReadRequest) (*StatusReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedStatusServer) mustEmbedUnimplementedStatusServer() {}

// RegisterStatusServer registers the server implementation.
func RegisterStatusServer(s grpc.ServiceRegistrar, srv StatusServer) {
	s.RegisterService(&Status_ServiceDesc, srv)
}

// Status_ServiceDesc is the grpc.ServiceDesc for the Status service.
var Status_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yakos.v1.Status",
	HandlerType: (*StatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "Read", Handler: _Status_Read_Handler},
	},
	Streams: []grpc.StreamDesc{},
}

func _Status_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/yakos.v1.Status/Read"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusServer).Read(ctx, req.(*StatusReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ---- Refresh service --------------------------------------------------------

// RefreshClient is the client API for the Refresh service.
type RefreshClient interface {
	Run(ctx context.Context, in *RefreshRunRequest, opts ...grpc.CallOption) (*RefreshRunResponse, error)
}

type refreshClient struct {
	cc grpc.ClientConnInterface
}

func NewRefreshClient(cc grpc.ClientConnInterface) RefreshClient {
	return &refreshClient{cc}
}

func (c *refreshClient) Run(ctx context.Context, in *RefreshRunRequest, opts ...grpc.CallOption) (*RefreshRunResponse, error) {
	out := new(RefreshRunResponse)
	err := c.cc.Invoke(ctx, "/yakos.v1.Refresh/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RefreshServer is the server API for the Refresh service.
type RefreshServer interface {
	Run(context.Context, *RefreshRunRequest) (*RefreshRunResponse, error)
	mustEmbedUnimplementedRefreshServer()
}

// UnimplementedRefreshServer must be embedded to have forward-compatible implementations.
type UnimplementedRefreshServer struct{}

func (UnimplementedRefreshServer) Run(context.Context, *RefreshRunRequest) (*RefreshRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedRefreshServer) mustEmbedUnimplementedRefreshServer() {}

// RegisterRefreshServer registers the server implementation.
func RegisterRefreshServer(s grpc.ServiceRegistrar, srv RefreshServer) {
	s.RegisterService(&Refresh_ServiceDesc, srv)
}

// Refresh_ServiceDesc is the grpc.ServiceDesc for the Refresh service.
var Refresh_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yakos.v1.Refresh",
	HandlerType: (*RefreshServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "Run", Handler: _Refresh_Run_Handler},
	},
	Streams: []grpc.StreamDesc{},
}

func _Refresh_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefreshServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/yakos.v1.Refresh/Run"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefreshServer).Run(ctx, req.(*RefreshRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}
